---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: tke-serverless-test
  name: tke-serverless
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tke-serverless
rules:
- apiGroups:
  - ""
  resources:
  - "pods"
  - "configmaps"
  - "secrets"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "update"
  - "patch"
  - "delete"
- apiGroups:
  - ""
  resources:
  - "nodes"
  - "namespaces"
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - "apps"
  resources:
  - "deployments"
  - "deployments/scale"
  - "replicasets"
  - "statefulsets"
  - "daemonsets"
  - "controllerrevisions"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "update"
  - "patch"
  - "delete"
- apiGroups:
  - "metrics.k8s.io"
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
- apiGroups:
  - argoproj.io
  resources:
  - workflowtaskresults
  - workflowtasksets
  - workflowtasksets/status
  - workflowtaskresults/finalizers
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flowcontrol.apiserver.k8s.io
  resources:
  - flowschemas
  - prioritylevelconfigurations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tke-serverless
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tke-serverless
subjects:
- kind: ServiceAccount
  namespace: tke-serverless-test
  name: tke-serverless
---
apiVersion: v1
kind: Secret
metadata:
  name: tke-serverless.service-account-token
  annotations:
    kubernetes.io/service-account.name: tke-serverless
type: kubernetes.io/service-account-token
