---
# 超级节点调度压力测试示例
# 该示例演示如何对超级节点进行调度压力测试
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  labels:
    supernode-scenario: "true"
  name: supernode-schedule-pressure-test
  namespace: tke-chaos-test
spec:
  entrypoint: main
  serviceAccountName: tke-chaos
  arguments:
    parameters:
    # 全局参数
    - name: chaos-image
      value: ccr.ccs.tencentyun.com/tkeimages/tke-chaos:v0.0.2
    - name: cluster-id  # 请修改为你的集群ID
      value: "cls-xxxxxxxx"
    - name: webhook-url  # 可选：企业微信群webhook地址
      value: ""
    - name: kubeconfig-secret-name
      value: "dest-cluster-kubeconfig"
    - name: chaos-type
      value: "supernode schedule pressure test"

    # 超级节点演练参数
    - name: scenario-type  # 调度压力测试
      value: "schedule-pressure"
    - name: supernode-selector  # 超级节点选择器
      value: "node.kubernetes.io/instance-type=eklet"
    - name: test-duration  # 测试持续时间
      value: "120s"
    - name: test-pod-count  # 测试Pod数量（调度压力测试专用）
      value: "100"

    # precheck参数
    - name: precheck-cluster-image
      value: "{{workflow.parameters.chaos-image}}"
    - name: precheck-configmap-name
      value: "tke-chaos-precheck-resource"
    - name: precheck-configmap-namespace
      value: "tke-chaos-test"
    - name: precheck-pods-health-ratio
      value: "0.9"
    - name: precheck-nodes-health-ratio
      value: "0.9"

  templates:
  - name: main
    steps:
    - - name: supernode-chaos-test
        arguments:
          parameters:
          - name: cluster-id
            value: "{{workflow.parameters.cluster-id}}"
          - name: webhook-url
            value: "{{workflow.parameters.webhook-url}}"
          - name: kubeconfig-secret-name
            value: "{{workflow.parameters.kubeconfig-secret-name}}"
          - name: chaos-type
            value: "{{workflow.parameters.chaos-type}}"
          - name: scenario-type
            value: "{{workflow.parameters.scenario-type}}"
          - name: supernode-selector
            value: "{{workflow.parameters.supernode-selector}}"
          - name: test-duration
            value: "{{workflow.parameters.test-duration}}"
          - name: test-pod-count
            value: "{{workflow.parameters.test-pod-count}}"
          # precheck参数
          - name: precheck-cluster-image
            value: "{{workflow.parameters.precheck-cluster-image}}"
          - name: check-configmap-name
            value: "{{workflow.parameters.precheck-configmap-name}}"
          - name: check-configmap-namespace
            value: "{{workflow.parameters.precheck-configmap-namespace}}"
          - name: pods-health-ratio
            value: "{{workflow.parameters.precheck-pods-health-ratio}}"
          - name: nodes-health-ratio
            value: "{{workflow.parameters.precheck-nodes-health-ratio}}"
        templateRef:
          name: supernode-template
          template: main
          clusterScope: true