---
# Description: Restore TKE managed cluster kube-scheduler component
# 
# 1. Performing pre-checks
# 2. Restoring the kube-scheduler component
# 3. Verifying the kube-scheduler status
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  labels:
    restore-kube-scheduler: "true"
  name: restore-kube-scheduler
  namespace: tke-chaos-test
spec:
  entrypoint: main
  serviceAccountName: tke-chaos
  arguments:
    parameters:
    - name: region  # Tencent Cloud region (e.g. ap-qingyuan)
      value: "<REGION>"
    - name: cluster-id  # Cluster ID
      value: "<CLUSTER_ID>"
    - name: secret-id  # Tencent Cloud API secret ID
      value: "<SECRET_ID>"
    - name: secret-key  # Tencent Cloud API secret key
      value: "<SECRET_KEY>"
    - name: kubeconfig-secret-name  # Secret name containing target cluster's kubeconfig
      value: "dest-cluster-kubeconfig"
    - name: precheck-configmap-name  # ConfigMap name for pre-check validation
      value: "tke-chaos-precheck-resource"
    - name: precheck-configmap-namespace  # Namespace of pre-check ConfigMap
      value: "tke-chaos-test"
  templates:
  - name: main
    steps:
    - - name: precheck
        arguments:
          parameters:
          - name: kubeconfig-secret-name
            value: "{{workflow.parameters.kubeconfig-secret-name}}"
          - name: precheck-configmap-name
            value: "{{workflow.parameters.precheck-configmap-name}}"
          - name: precheck-configmap-namespace
            value: "{{workflow.parameters.precheck-configmap-namespace}}"
          - name: source
            value: |
              kubectl get -n {{workflow.parameters.precheck-configmap-namespace}} configmap {{workflow.parameters.precheck-configmap-name}}
        templateRef:
          name: kubectl-cmd
          template: kubectl-script
          clusterScope: true
    - - name: restore-scheduler
        arguments:
          parameters:
          - name: args
            value: |
              {
                  "secretId": "{{workflow.parameters.secret-id}}",
                  "secretKey": "{{workflow.parameters.secret-key}}",
                  "region": "{{workflow.parameters.region}}",
                  "clusterId": "{{workflow.parameters.cluster-id}}",
                  "component": "kube-scheduler",
                  "action": "restore"
              }
        templateRef:
          name: tke-master-manager-template
          template: caller
          clusterScope: true
    - - name: delay
        template: delay
        arguments:
          parameters:
          - name: duration
            value: "20s"
    - - name: get-scheduler-status
        arguments:
          parameters:
          - name: args
            value: |
              {
                  "secretId": "{{workflow.parameters.secret-id}}",
                  "secretKey": "{{workflow.parameters.secret-key}}",
                  "region": "{{workflow.parameters.region}}",
                  "clusterId": "{{workflow.parameters.cluster-id}}",
                  "component": "kube-scheduler",
                  "action": "describe"
              }
        templateRef:
          name: tke-master-manager-template
          template: caller
          clusterScope: true

  - name: delay
    inputs:
      parameters:
      - name: duration
    suspend:
      duration: "{{inputs.parameters.duration}}"
