---
# 精确沙箱复用测试示例
# 完全按照需求：测量Pod创建时间（不含启动时间），20秒后销毁，对比分析沙箱复用效果
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: precise-sandbox-reuse-test-
  namespace: tke-chaos-test
  labels:
    test-type: "deployment-sandbox-reuse"
    example: "precise-measurement"
spec:
  serviceAccountName: tke-chaos
  entrypoint: deployment-sandbox-test
  arguments:
    parameters:
    # 基础配置
    - name: cluster-id
      value: "tke-cluster"
    - name: webhook-url
      value: ""  # 建议配置企业微信通知获取详细结果
    
    # 测试配置 - 精确测量配置
    - name: kubeconfig-secret-name
      value: ""
    - name: deployment-name-prefix
      value: "precise-sandbox-test"
    - name: replicas
      value: "1"  # 支持任意Pod数量
    - name: pod-image
      value: "nginx:alpine"
    - name: namespace
      value: "tke-chaos-test"
    - name: test-iterations
      value: "2"  # 两次测试：基准测试 + 沙箱复用测试
    - name: delay-between-tests
      value: "20s"  # 严格按照需求20秒后销毁
    
    # 资源配置 - 标准配置
    - name: cpu-request
      value: "100m"
    - name: memory-request
      value: "128Mi"
    - name: cpu-limit
      value: "200m"
    - name: memory-limit
      value: "256Mi"

  workflowTemplateRef:
    name: supernode-sandbox-deployment-template
    clusterScope: true