---
# 企业微信通知测试示例
# 用于测试企业微信通知功能是否正常工作
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-wechat-notification-
  namespace: tke-chaos-test
  labels:
    test-type: "wechat-notification-test"
spec:
  serviceAccountName: tke-chaos
  entrypoint: deployment-sandbox-test
  arguments:
    parameters:
    # 基础配置
    - name: cluster-id
      value: "test-cluster"
    - name: webhook-url
      value: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=YOUR_WEBHOOK_KEY"  # 请替换为实际的webhook地址
    
    # 测试配置 - 快速测试
    - name: kubeconfig-secret-name
      value: ""
    - name: deployment-name-prefix
      value: "wechat-test"
    - name: replicas
      value: "1"  # 单个Pod快速测试
    - name: pod-image
      value: "nginx:alpine"
    - name: namespace
      value: "tke-chaos-test"
    - name: test-iterations
      value: "2"  # 两次测试：基准测试 + 沙箱复用测试
    - name: delay-between-tests
      value: "20s"
    
    # 资源配置 - 轻量级
    - name: cpu-request
      value: "50m"
    - name: memory-request
      value: "64Mi"
    - name: cpu-limit
      value: "100m"
    - name: memory-limit
      value: "128Mi"

  workflowTemplateRef:
    name: supernode-sandbox-deployment-template
    clusterScope: true