---
# 镜像拉取性能测试工作流
# Image Pull Performance Test Workflow
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  labels:
    image-pull-test: "true"
  name: image-pull-test
  namespace: tke-chaos-test
spec:
  entrypoint: main
  serviceAccountName: tke-chaos
  arguments:
    parameters:
    - name: test-images  # 测试镜像列表，逗号分隔
      value: "nginx:alpine,redis:alpine,mysql:8.0,elasticsearch:7.17.0"
    - name: concurrent-pulls  # 并发拉取数量
      value: "10"
    - name: test-rounds  # 测试轮数
      value: "3"
    - name: supernode-selector  # 超级节点选择器
      value: "node.kubernetes.io/instance-type=eklet"
    - name: kubeconfig-secret-name  # 目标集群kubeconfig secret名称
      value: "dest-cluster-kubeconfig"
  templates:
  - name: main
    steps:
    - - name: image-pull-test
        arguments:
          parameters:
          - name: test-images
            value: "{{workflow.parameters.test-images}}"
          - name: concurrent-pulls
            value: "{{workflow.parameters.concurrent-pulls}}"
          - name: test-rounds
            value: "{{workflow.parameters.test-rounds}}"
          - name: supernode-selector
            value: "{{workflow.parameters.supernode-selector}}"
          - name: kubeconfig-secret-name
            value: "{{workflow.parameters.kubeconfig-secret-name}}"
        templateRef:
          name: image-pull-template
          template: main
          clusterScope: true