---
# Description: TKE Managed Cluster kube-scheduler Shutdown Test Scenario
# 
# This workflow simulates and tests the kube-scheduler outage scenario with following steps:
# 1. Performing pre-checks
# 2. Shutting down the kube-scheduler component
# 3. Verifying the shutdown status
# 4. Restoring the kube-scheduler
# 5. Verifying the restoration
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  labels:
    scheduler-shutdown-scenario: "true"
  name: scheduler-shutdown-scenario
  namespace: tke-chaos-test
spec:
  entrypoint: main
  serviceAccountName: tke-chaos
  arguments:
    parameters:
    - name: region  # Tencent Cloud region (e.g. ap-qingyuan)
      value: "<REGION>"
    - name: cluster-id  # Cluster ID
      value: "<CLUSTER_ID>"
    - name: secret-id  # Tencent Cloud API secret ID
      value: "<SECRET_ID>"
    - name: secret-key  # Tencent Cloud API secret key
      value: "<SECRET_KEY>"
    - name: kubeconfig-secret-name  # Secret name containing target cluster's kubeconfig
      value: "dest-cluster-kubeconfig"
    - name: precheck-configmap-name  # ConfigMap name for pre-check validation
      value: "tke-chaos-precheck-resource"
    - name: precheck-configmap-namespace  # Namespace of pre-check ConfigMap
      value: "tke-chaos-test"
  templates:
  - name: main
    steps:
    - - name: precheck
        arguments:
          parameters:
          - name: kubeconfig-secret-name
            value: "{{workflow.parameters.kubeconfig-secret-name}}"
          - name: precheck-configmap-name
            value: "{{workflow.parameters.precheck-configmap-name}}"
          - name: precheck-configmap-namespace
            value: "{{workflow.parameters.precheck-configmap-namespace}}"
          - name: source
            value: |
              kubectl get -n {{workflow.parameters.precheck-configmap-namespace}} configmap {{workflow.parameters.precheck-configmap-name}}
        templateRef:
          name: kubectl-cmd
          template: kubectl-script
          clusterScope: true
    - - name: suspend-1
        template: suspend
    - - name: shutdown-scheduler
        arguments:
          parameters:
          - name: args
            value: |
              {
                  "secretId": "{{workflow.parameters.secret-id}}",
                  "secretKey": "{{workflow.parameters.secret-key}}",
                  "region": "{{workflow.parameters.region}}",
                  "clusterId": "{{workflow.parameters.cluster-id}}",
                  "component": "kube-scheduler",
                  "action": "shutdown"
              }
        templateRef:
          name: tke-master-manager-template
          template: caller
          clusterScope: true
    - - name: delay-1
        template: delay
        arguments:
          parameters:
          - name: duration
            value: "20s"
    - - name: get-scheduler-status-1
        arguments:
          parameters:
          - name: args
            value: |
              {
                  "secretId": "{{workflow.parameters.secret-id}}",
                  "secretKey": "{{workflow.parameters.secret-key}}",
                  "region": "{{workflow.parameters.region}}",
                  "clusterId": "{{workflow.parameters.cluster-id}}",
                  "component": "kube-scheduler",
                  "action": "describe"
              }
        templateRef:
          name: tke-master-manager-template
          template: caller
          clusterScope: true
    - - name: suspend-2
        template: suspend
    - - name: restore-scheduler
        arguments:
          parameters:
          - name: args
            value: |
              {
                  "secretId": "{{workflow.parameters.secret-id}}",
                  "secretKey": "{{workflow.parameters.secret-key}}",
                  "region": "{{workflow.parameters.region}}",
                  "clusterId": "{{workflow.parameters.cluster-id}}",
                  "component": "kube-scheduler",
                  "action": "restore"
              }
        templateRef:
          name: tke-master-manager-template
          template: caller
          clusterScope: true
    - - name: delay-2
        template: delay
        arguments:
          parameters:
          - name: duration
            value: "20s"
    - - name: get-scheduler-status-2
        arguments:
          parameters:
          - name: args
            value: |
              {
                  "secretId": "{{workflow.parameters.secret-id}}",
                  "secretKey": "{{workflow.parameters.secret-key}}",
                  "region": "{{workflow.parameters.region}}",
                  "clusterId": "{{workflow.parameters.cluster-id}}",
                  "component": "kube-scheduler",
                  "action": "describe"
              }
        templateRef:
          name: tke-master-manager-template
          template: caller
          clusterScope: true

  - name: suspend
    suspend: {}

  - name: delay
    inputs:
      parameters:
      - name: duration
    suspend:
      duration: "{{inputs.parameters.duration}}"
