---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: block-namespace-deletion-scenario
  namespace: tke-chaos-test
spec:
  entrypoint: main
  serviceAccountName: tke-chaos
  arguments:
    parameters:
    - name: kubeconfig-secret-name
      value: "dest-cluster-kubeconfig"
    - name: block-namespace-deletion-manifest
      value: |
        apiVersion: constraints.gatekeeper.sh/v1beta1
        kind: BlockNamespaceDeletion
        metadata:
          name: tke-chaos-test
        spec:
          enforcementAction: deny
          match:
            kinds:
            - apiGroups:
              - '*'
              kinds:
              - Namespace
    - name: pod-manifest
      value: |
        apiVersion: v1
        kind: Pod
        metadata:
          name: pod-76498
          namespace: tke-chaos-ns-76498
          labels:
            pod-name: pod-76498
        spec:
          nodeSelector:
            kubernetes.io/hostname: non-existent-node-3060282720
          tolerations:
          - key: node.kubernetes.io/unreachable
            operator: Exists
            effect: NoSchedule
          containers:
          - name: busybox
            image: busybox:1.37.0
            command: ["sleep", "3600"]
          restartPolicy: Never
  templates:
  - name: main
    steps:
    - - name: create-block-namespace-deletion
        arguments:
          parameters:
          - name: action
            value: "create"
          - name: manifest
            value: "{{workflow.parameters.block-namespace-deletion-manifest}}"
          - name: kubeconfig-secret-name
            value: "{{workflow.parameters.kubeconfig-secret-name}}"
        templateRef:
          name: kubectl-cmd
          template: kubectl-mutating-cmd
          clusterScope: true
    - - name: create-namespace
        arguments:
          parameters:
          - name: cmd
            value: "create namespace tke-chaos-ns-76498"
          - name: kubeconfig-secret-name
            value: "{{workflow.parameters.kubeconfig-secret-name}}"
        templateRef:
          name: kubectl-cmd
          template: kubectl-cmd
          clusterScope: true
    - - name: create-pod-in-namespace
        arguments:
          parameters:
          - name: action
            value: "create"
          - name: manifest
            value: "{{workflow.parameters.pod-manifest}}"
          - name: kubeconfig-secret-name
            value: "{{workflow.parameters.kubeconfig-secret-name}}"
        templateRef:
          name: kubectl-cmd
          template: kubectl-mutating-cmd
          clusterScope: true
    - - name: delete-namespace-with-pod-in-namespace
        continueOn:
          failed: true
          error: true
        arguments:
          parameters:
          - name: cmd
            value: "delete namespace tke-chaos-ns-76498"
          - name: kubeconfig-secret-name
            value: "{{workflow.parameters.kubeconfig-secret-name}}"
        templateRef:
          name: kubectl-cmd
          template: kubectl-cmd
          clusterScope: true
    # - - name: suspend
    #     template: suspend
    - - name: delete-pod-in-namespace
        arguments:
          parameters:
          - name: action
            value: "delete"
          - name: manifest
            value: "{{workflow.parameters.pod-manifest}}"
          - name: kubeconfig-secret-name
            value: "{{workflow.parameters.kubeconfig-secret-name}}"
        templateRef:
          name: kubectl-cmd
          template: kubectl-mutating-cmd
          clusterScope: true
    - - name: delete-namespace-without-pod-in-namespace
        arguments:
          parameters:
          - name: cmd
            value: "delete namespace tke-chaos-ns-76498"
          - name: kubeconfig-secret-name
            value: "{{workflow.parameters.kubeconfig-secret-name}}"
        templateRef:
          name: kubectl-cmd
          template: kubectl-cmd
          clusterScope: true
    - - name: delete-block-namespace-deletion
        arguments:
          parameters:
          - name: action
            value: "delete"
          - name: manifest
            value: "{{workflow.parameters.block-namespace-deletion-manifest}}"
          - name: kubeconfig-secret-name
            value: "{{workflow.parameters.kubeconfig-secret-name}}"
        templateRef:
          name: kubectl-cmd
          template: kubectl-mutating-cmd
          clusterScope: true

  - name: suspend
    suspend: {}
