---
# 功能说明：腾讯云超级节点演练场景
# 支持的演练类型：
# 1. schedule-pressure: 超级节点Pod调度压力测试
# 2. resource-limit: 超级节点资源限制测试
# 3. failure-simulation: 超级节点故障模拟测试
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  labels:
    supernode-scenario: "true"
  name: supernode-scenario
  namespace: tke-chaos-test
spec:
  entrypoint: main
  serviceAccountName: tke-chaos
  arguments:
    parameters:
    # 全局参数
    - name: chaos-image
      value: ccr.ccs.tencentyun.com/tkeimages/tke-chaos:v0.0.2
    - name: cluster-id  # 演练集群ID
      value: "未知"
    - name: webhook-url  # 企业微信群webhook地址
      value: ""
    - name: kubeconfig-secret-name  # 目标集群接入kubeconfig的secret名称
      value: "dest-cluster-kubeconfig"
    - name: chaos-type  # 演练类型
      value: "supernode chaos test"

    # 超级节点演练参数
    - name: scenario-type  # 演练场景类型: schedule-pressure/resource-limit/failure-simulation
      value: "schedule-pressure"
    - name: supernode-selector  # 超级节点选择器
      value: "node.kubernetes.io/instance-type=eklet"
    - name: test-duration  # 测试持续时间
      value: "60s"
    - name: test-pod-count  # 测试Pod数量(仅用于调度压力测试)
      value: "50"
    - name: cpu-stress-cores  # CPU压力测试核心数(仅用于资源限制测试)
      value: "2"
    - name: memory-stress-size  # 内存压力测试大小(仅用于资源限制测试)
      value: "1G"

    # precheck参数
    - name: precheck-cluster-image  # 前置检查工具镜像
      value: "{{workflow.parameters.chaos-image}}"
    - name: precheck-configmap-name  # 前置检查检测的configmap名称
      value: "tke-chaos-precheck-resource"
    - name: precheck-configmap-namespace  # 前置检查检测的configmap命名空间
      value: "tke-chaos-test"
    - name: precheck-pods-health-ratio  # 检测集群pods健康率
      value: "0.9"
    - name: precheck-nodes-health-ratio  # 集群节点健康率
      value: "0.9"

  templates:
  - name: main
    steps:
    - - name: supernode-chaos-test
        arguments:
          parameters:
          - name: cluster-id
            value: "{{workflow.parameters.cluster-id}}"
          - name: webhook-url
            value: "{{workflow.parameters.webhook-url}}"
          - name: kubeconfig-secret-name
            value: "{{workflow.parameters.kubeconfig-secret-name}}"
          - name: chaos-type
            value: "{{workflow.parameters.chaos-type}}"
          - name: scenario-type
            value: "{{workflow.parameters.scenario-type}}"
          - name: supernode-selector
            value: "{{workflow.parameters.supernode-selector}}"
          - name: test-duration
            value: "{{workflow.parameters.test-duration}}"
          - name: test-pod-count
            value: "{{workflow.parameters.test-pod-count}}"
          - name: cpu-stress-cores
            value: "{{workflow.parameters.cpu-stress-cores}}"
          - name: memory-stress-size
            value: "{{workflow.parameters.memory-stress-size}}"
          # precheck参数
          - name: precheck-cluster-image
            value: "{{workflow.parameters.precheck-cluster-image}}"
          - name: check-configmap-name
            value: "{{workflow.parameters.precheck-configmap-name}}"
          - name: check-configmap-namespace
            value: "{{workflow.parameters.precheck-configmap-namespace}}"
          - name: pods-health-ratio
            value: "{{workflow.parameters.precheck-pods-health-ratio}}"
          - name: nodes-health-ratio
            value: "{{workflow.parameters.precheck-nodes-health-ratio}}"
        templateRef:
          name: supernode-template
          template: main
          clusterScope: true