# 网络性能测试配置
# Network Performance Test Configuration

# 测试配置 | Test Configuration
test_config:
  # 基础配置 | Basic Configuration
  namespace: "tke-network-test"
  test_duration: "300s"  # 5分钟测试
  
  # Pod配置 | Pod Configuration
  client_pods: 5          # 客户端Pod数量
  server_pods: 3          # 服务端Pod数量
  
  # 网络测试参数 | Network Test Parameters
  network_tests:
    # 延迟测试 | Latency Test
    latency:
      enabled: true
      ping_count: 100
      ping_interval: "0.1s"
      timeout: "5s"
      
    # 带宽测试 | Bandwidth Test  
    bandwidth:
      enabled: true
      duration: "30s"
      parallel_streams: 4
      buffer_size: "128K"
      
    # 吞吐量测试 | Throughput Test
    throughput:
      enabled: true
      packet_sizes: [64, 512, 1024, 1500]  # bytes
      test_duration: "60s"

# 镜像配置 | Image Configuration
images:
  network_client: "nicolaka/netshoot:latest"
  network_server: "nginx:alpine"
  iperf_server: "networkstatic/iperf3:latest"

# 资源配置 | Resource Configuration
resources:
  client_pods:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
      
  server_pods:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"

# 性能阈值 | Performance Thresholds
thresholds:
  latency:
    excellent: 1.0    # ms
    good: 5.0         # ms
    warning: 10.0     # ms
    
  bandwidth:
    excellent: 1000   # Mbps
    good: 500         # Mbps
    warning: 100      # Mbps
    
  packet_loss:
    excellent: 0.1    # %
    good: 1.0         # %
    warning: 5.0      # %

# 超级节点配置 | SuperNode Configuration
supernode:
  selector: "node.kubernetes.io/instance-type=eklet"
  distribution: "round-robin"  # round-robin | random | balanced