---
# 功能说明: 控制面负载信息采集, 使用kubectl top命令, 获取k8s集群中etcd, apiserver, master节点负载信息
# 参数说明:
#   get-metrics模版参数说明:
#     1. kubeconfig-secret-name: 用于指定接入的K8s集群的kubeconfig凭证的secret名称, 如果为空，则默认为当前集群
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: controll-plan-metrics-collect-template
spec:
  entrypoint: get-metrics
  templates:
  - name: get-metrics
    inputs:
      parameters:
      - name: kubeconfig-secret-name
        description: "用于指定接入的K8s集群的kubeconfig凭证的secret名称, 如果为空，则默认为当前集群"
    dag:
      tasks:
      - name: get-metrics
        arguments:
          parameters:
          - name: kubeconfig-secret-name
            value: "{{inputs.parameters.kubeconfig-secret-name}}"
          - name: source
            value: |
              #!/bin/bash
              echo ""
              echo "=== APIServer Metrics ==="
              kubectl top pod -n kube-system | grep kube-apiserver
              echo "=== ETCD Metrics ==="
              kubectl top pod -n kube-system | grep etcd
              echo "=== Master Node Metrics ==="
              kubectl top node -l node-role.kubernetes.io/master=true
        templateRef:
          name: kubectl-cmd
          template: kubectl-script
          clusterScope: true
    outputs:
      parameters:
      - name: result
        valueFrom:
          parameter: "{{tasks.get-metrics.outputs.parameters.result}}"
