---
# Description: Template for interacting with Tencent Cloud TKE API
# API Documentation: https://cloud.tencent.com/document/api
#
# Parameters:
#   args: JSON format parameters for TKE API call. Required fields:
#     - secretId: Tencent Cloud API secret ID (Manage at: https://console.cloud.tencent.com/cam/capi)
#     - secretKey: Tencent Cloud API secret key
#     - region: Cloud region (e.g. ap-guangzhou)
#     - clusterId: TKE cluster ID
#     - component: Kubernetes component name (e.g. kube-apiserver, kube-controller-manager, kube-scheduler)
#     - action: API action name (e.g. describe, shutdown, restore)
#
# Example args value:
# {
#   "secretId": "<SECRET_ID>",
#   "secretKey": "<SECRET_KEY>",
#   "region": "ap-qingyuan",
#   "clusterId": "cls-12345678",
#   "component": "kube-apiserver",
#   "action": "describe"
# }
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: tke-master-manager-template
spec:
  entrypoint: caller
  templates:
  - name: caller
    inputs:
      parameters:
      - name: image
        default: "ccr.ccs.tencentyun.com/tkeimages/tke-chaos:v0.0.2"
      - name: args
    container:
      image: "{{inputs.parameters.image}}"
      command:
      - /kubestress
      - mastermanager
      - --provider=tke
      - --args={{inputs.parameters.args}}
    outputs:
      parameters:
      - name: response
        valueFrom:
          default: "null"
          path: /tmp/response.txt
